### ISSUE TITLE
Outer Loop

### ISSUE THREAD

**Issue by mayuri95** [ElectionAuditWare/audit-conductor#10]
Need to add a module, for the outer loop to calculate risk and decide whether to escalate the audit.

**Comment by tom-votes** [comment]
We do now have a "stopping condition," but it's simply that we've run out of ballot, given that we're running a fixed number for each audit/contest.

**Comment by mayuri95** [comment]
We still need a loop for the Bayesian stuff, so I'll keep this open

**Comment by mayuri95** [comment]
Done :)
