### ISSUE TITLE
Ballot Manifest

### ISSUE THREAD

**Issue by mayuri95** [ElectionAuditWare/audit-conductor#18]
Define the format for a ballot manifest.

Maybe this should be the same format as the CORLA? This is documented in the CORLA tool.

**Comment by nealmcb** [comment]
Ballot sheet manifests as used in ColoradoRLA are documented in book.html.  You can download that (but not view it in formatted form directly) at:
https://raw.githubusercontent.com/FreeAndFair/ColoradoRLA/fbbc9aba46c4db4b9c7349a855397a27439d2a5b/docs/book.html

I.e.

> ballot manifest - A document that describes how ballot cards are organized and stored, and relates a Cast Vote Records to the physical location in which the tabulated ballot card is stored. The ballot manifest specifies the physical location of a ballot card to allow    staff to find the specific ballot card represented by a given CVR. A ballot manifest will contain the following information: 
 county ID, tabulator ID, batch ID, the number of ballot cards in each batch, and the storage location where the batch is secured following tabulation.                                                                                                                         

It notes a sample manifest:
https://github.com/FreeAndFair/ColoradoRLA/blob/fbbc9aba46c4db4b9c7349a855397a27439d2a5b/docs/samples/manifest-dq.csv

More complete examples of working manifests and cvrs are at e.g.https://github.com/FreeAndFair/ColoradoRLA/tree/fbbc9aba46c4db4b9c7349a855397a27439d2a5b/test/e-1

**Comment by JohnMcCarthy** [comment]
Ballot manifest format approved by RI election officials is now frozen per attached email msg from Mark Lindeman and attached tab-separated .txt
[Ballot Manifest Template.txt](https://github.com/ElectionAuditWare/audit-conductor/files/2729965/Ballot.Manifest.Template.txt)
 template
[Lindeman email re ballot manifest format.txt](https://github.com/ElectionAuditWare/audit-conductor/files/2729963/Lindeman.email.re.ballot.manifest.format.txt)

**Comment by mayuri95** [comment]
I'm a bit confused on this. The example ballot manifest has 

box 1, 9050 sheets, 85 first imprint ID, 9034 first imprint ID

Is this a typo? If the imprint IDs are implicit positions (which is how I had been interpreting them), then 9034-85+1 should be 9050, which it isn't. Not sure if this is a typo in the example manifest or the imprints mean something different? Leaving this open until that is clarified

**Comment by PlauditsForAudits** [comment]
Yes, that's a typo. The imprints should be unique: it may be possible to have a skip, but isn't possible to reuse. (Dunno how rigorous the validation will be for the pilot.) --This is Mark, by the way.

**Comment by mayuri95** [comment]
Defined and done :)
