### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by mayuri95** [ElectionAuditWare/audit-conductor#2]
We need a requirements.txt file so that this can be run easily on the server.

Based on the README and initial testing, we need at least:
hypothesis
matplotlib
numpy
scipy
cryptorandom
pytest
flask
sampler

Are there any others? Do we need specific versions?

**Comment by tom-votes** [comment]
I've added the result of

    pip freeze > requirements.txt

I'll close this ticket after we've verified it working on someone else's machine

**Comment by mayuri95** [comment]
can we add pytest as a requirement here?

**Comment by mayuri95** [comment]
already hosted, so this is not high-priority.
