### ISSUE TITLE
Bug in computing T

### ISSUE THREAD

**Issue by mayuri95** [ElectionAuditWare/audit-conductor#23]
As @zperumal pointed out, the risk calculations aren't always correct.
"When I choose the first candidate for all cases, it says to do a full recount, vs election verified."

**Comment by tom-votes** [comment]
So, this issue is only on the hosted-on-MIT-server one, right?

If so, it's almost definitely an issue which I'm working on, which is to clear out data from previous runs (i.e. if someone previously ran a different audit on the MIT server)

**Comment by tom-votes** [comment]
I've added a very simple `/reset` page that people can use for testing on MIT servers.
