### ISSUE TITLE
AJAX Error

### ISSUE THREAD

**Issue by mayuri95** [ElectionAuditWare/audit-conductor#3]
If I run `FLASK_APP=server.py flask run`, then click save, I get the following error:

![image](https://user-images.githubusercontent.com/8022782/50485935-5de4e500-09c5-11e9-868b-3fdb4f98bcae.png)

**Comment by tom-votes** [comment]
I think this was fixed with ```git submodule init```, right?

**Comment by mayuri95** [comment]
No, it wasn't :(

**Comment by tom-votes** [comment]
@nealmcb is this the same sampler error you were seeing? We're pulling in from a submodule of ```OpenRLA``` so we shouldn't need to ```pip install```.

**Comment by nealmcb** [comment]
This is what I got:

```
  File "/srv/s/electionaudits/audit-conductor/server.py", line 38, in <module>
    import sampler                                            
ModuleNotFoundError: No module named 'sampler'                         
```
So I referred instead to my own version of sampler from the well-tested `python3-port` branch of https://github.com/nealmcb/rivest-sampler-tests/tree/python3-port

see https://github.com/nealmcb/rivest-sampler-tests/pull/1

**Comment by tom-votes** [comment]
The submodule problem may be a red herring but do you mind trying with `git submodule update --init --recursive`?

**Comment by tom-votes** [comment]
@nealmcb great, I'll probably switch to your `python3-port` version. It looks similar to the by-hand python3 update I did on a different fork: https://github.com/ElectionAuditWare/OpenRLA/commit/3041c962badb155ded12c0071bea8c7f1491262e

**Comment by mayuri95** [comment]
Mine doesn't get fixed even after the update.

**Comment by mayuri95** [comment]
The git submodule update, at least for me, does not import Neal's version of the sampler algorithm. Rather, it's pulling from the master branch, which causes all kinds of problems. As a heads-up, I actually had to remove the rivest-sampler-tests directory and clone from the right branch with:

git clone --single-branch --branch python3-port https://github.com/nealmcb/rivest-sampler-tests.git

**Comment by mayuri95** [comment]
resolved.
