### ISSUE TITLE
Add time data to audit cvr's - begin, first reject, accept

### ISSUE THREAD

**Issue by JohnMcCarthy** [ElectionAuditWare/audit-conductor#31]
We need to capture timing data we can analyze later to improve RLA efficiency.

One way to do that is to capture the time when someone begins to enter data for an "audit cvr" -- i.e., the cvr that is created by entering vote interpretations for selected contests from a particular sample ballot selected to be audited. We could then capture the (first) time the user rejects the selections when prompted to confirm, and finally the time when the user "accepts" the votes for that particular ballot. When the software closes out that transaction, it should write those three times as three additional fields on the audit cvr for that ballot.

**Comment by mayuri95** [comment]
Me and @zperumal will be working on getting this working.

**Comment by tom-votes** [comment]
Did this in https://github.com/ElectionAuditWare/audit-conductor/commit/c5adada4aa4ede0e44264e1ea6f0a08857a24a61

Sorry, I hadn't seen your note @mayuri95 - just worked on it when I was stuck on something else.

**Comment by mayuri95** [comment]
no worries, my implementation was uglier than this.
