### ISSUE TITLE
Logging Progress Issue

### ISSUE THREAD

**Issue by mayuri95** [ElectionAuditWare/audit-conductor#34]
As @JohnMcCarthy pointed out, in the logging for the comparison audit, some of the (reported, actual) pairs are being printed twice.

**Comment by mayuri95** [comment]
@JohnMcCarthy suggested this format:

CONTEST                     Original CVR  from scan   Audit CVR from sampled ballot  Match?
Senator in Congress        Whilehouse                           Whilehouse                            yes
Rept in Cong Dist 1          Cicilline                                   Cicilline                                   yes
Governor                           Gilbert                                    under vote                             no  
Lt Governor                                         etc
etc.                                                             etc

for the in-progress message

**Comment by mayuri95** [comment]
fixed and pushed by @zperumal 
cc @JohnMcCarthy if you want to test this :)

**Comment by JohnMcCarthy** [comment]
I needed to clear my cache and cookies to get rid of an AJAX fail.
ballot polling for Portsmouth then ran ok.

Ballot comparison for Bristol went ok through the first ball, bu then 
when I entered votes for the second ballot and tried pushing the Confirm 
button, I got another AJAX error msg:
AJAX failure!: 
{"readyState":4,"responseText":"<html>\r\n<head><title>502 Bad 
Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 
Bad 
Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n","status":502,"statusText":"Bad Gateway"}

John

**Comment by mayuri95** [comment]
I can't replicate this -- @zperumal ?
