### ISSUE TITLE
Hosting on Webserver

### ISSUE THREAD

**Issue by mayuri95** [ElectionAuditWare/audit-conductor#4]
There are a few things that need to be set up to get this hosted on an MIT webserver:
-Need a requirements.txt
-Need a simple command to run the website, preferably a python command (like `python server.py`) - this might imply that we should make a __main__ function in server.py?
-Need to have a list of all routes - if we click a button, are we redirecting to a different URL? Which ones?

**Comment by tom-votes** [comment]
- ```requirements.txt``` added!
  - The command to run should just be ```FLASK_APP=server.py flask run --port 80```. (May also need ```-host=0.0.0.0```)
   - Everything happens on the main page with ajax requests, so going to the index (by default ```http://127.0.0.1:5000/```) should be enough

**Comment by mayuri95** [comment]
I still haven't been able to get most of the website's functionality working.

**Comment by mayuri95** [comment]
resolved and hosted
