### ISSUE TITLE
Git submodule update errors

### ISSUE THREAD

**Issue by mayuri95** [ElectionAuditWare/audit-conductor#5]
Running `git submodule update` gives me the following error:
![image](https://user-images.githubusercontent.com/8022782/50486079-20cd2280-09c6-11e9-93ae-ddadce680807.png)

**Comment by mayuri95** [comment]
Is this a permissions issue?

**Comment by tom-votes** [comment]
Is this fixed on master with https://github.com/ElectionAuditWare/audit-conductor/commit/2868d318f24f46b19be230074ec1b060b72337aa ?

**Comment by mayuri95** [comment]
yes, leaving this open until the first new person can try this and get it working :)

**Comment by mayuri95** [comment]
If I re-clone and retry this, I get the following stacktrace:
![image](https://user-images.githubusercontent.com/8022782/50596326-dfc78900-0e71-11e9-9343-adc044efed6d.png)

**Comment by nealmcb** [comment]
It would help if you could attach text rather than images. Just surround a copy-paste with three backticks (`)

**Comment by nealmcb** [comment]
I get this similar error, after I just pulled f9ec17c 2019-01-02 Add autofocus for form elements [tom-votes]

I got this when setting up submodules according to README.md instructions:
 
```
$ git submodule update --init --recursive
Submodule 'OpenRLA' (https://github.com/ElectionAuditWare/OpenRLA) registered for path 'OpenRLA'
Submodule 'RIWAVE' (https://github.com/zperumal/RIWAVE) registered for path 'RIWAVE'
Submodule 'rivest-sampler-tests' (https://github.com/nealmcb/rivest-sampler-tests) registered for path 'rivest-sampler-tests'
Cloning into '/srv/s/electionaudits/audit-conductor/OpenRLA'...
Cloning into '/srv/s/electionaudits/audit-conductor/RIWAVE'...
Cloning into '/srv/s/electionaudits/audit-conductor/rivest-sampler-tests'...
Submodule path 'OpenRLA': checked out '3041c962badb155ded12c0071bea8c7f1491262e'
fatal: No url found for submodule path 'OpenRLA/DKDHondt14/RLA' in .gitmodules
Submodule path 'RIWAVE': checked out '9f0437df6ee3967bf1d32c70d1d25b4306c33494'
Submodule path 'rivest-sampler-tests': checked out '4464b865cbb7d891455d5d753012413b1fc8121d'
Failed to recurse into submodule path 'OpenRLA'
```

**Comment by nealmcb** [comment]
I think I fixed this by just dropping the now-obsolete OpenRLA submodule entirely in https://github.com/ElectionAuditWare/audit-conductor/pull/21
