### ISSUE TITLE
Data Format for Comparison Audit

### ISSUE THREAD

**Issue by mayuri95** [ElectionAuditWare/audit-conductor#7]
Format for the audit interpretations: Each ballot represented as a dictionary from ballot ID to a contest ID to a string representing choice on the ballot - we need to get the CVR interpretations in the same format.

**Comment by mayuri95** [comment]
Currently, the CVR data is being converted by Stephanie into the format that the CORLA tool uses (Dominion export format).
-4 header rows, then data rows
Besides the headers, it should be a plain CSV -- can we work with this format?

**Comment by mayuri95** [comment]
Maybe we should have manual and CVRs in the exact same format, like Neal suggested?

**Comment by JohnMcCarthy** [comment]
I agree that we should have manual and CVRs in the exact same format, like Neal suggested.
And we need to get ballot comparison audits working asap!

**Comment by mayuri95** [comment]
CVR representation is done.
